name: Parse parameters from workflow config file
inputs:
  working-directory:
    description: Working directory
    required: true
  config-filename:
    description: Path to config file
    required: false
    default: 'workflow-configs.yml'
  prerelease_version:
    description: Pre release version
    required: true
outputs:
  test_release_url:
    description: "Test release url" 
    value: ${{steps.parse-yaml.outputs.test_release_url}}
  test_staging_url:
    description: "Test staging url"
    value: ${{steps.parse-yaml.outputs.test_staging_url}}
  test_script: 
    description: "Test script" 
    value: ${{steps.parse-yaml.outputs.test_script}}
  s3_base_target:
    description: "S3 base target"
    value: ${{steps.parse-yaml.outputs.s3_base_target}}
runs:
  using: "composite"
  steps:    
    - name: Read Yaml and Set Step Outputs
      id: parse-yaml
      shell: bash
      env:
        CONFIG_FILE_PATH: ${{ format('{0}/{1}',inputs.working-directory, inputs.config-filename) }}
      run: |
        TEST_RELEASE_BASE_URL=$(yq '.base_url.release' $CONFIG_FILE_PATH)
        TEST_STAGING_BASE_URL=$(yq '.base_url.staging' $CONFIG_FILE_PATH)
        OVERRIDE_PARAM_NAME=$(yq '.override_param_name' $CONFIG_FILE_PATH)
        TEST_ENTRY_POINT=$(yq '.test_entry_point' $CONFIG_FILE_PATH)
        S3_BASE_TARGET=$(yq '.s3_base_target' $CONFIG_FILE_PATH)
        
        TEST_RELEASE_URL="${TEST_RELEASE_BASE_URL}/index.html?${OVERRIDE_PARAM_NAME}=${{inputs.prerelease_version}}"
        TEST_STAGING_URL="${TEST_STAGING_BASE_URL}/index.html?${OVERRIDE_PARAM_NAME}=${{inputs.prerelease_version}}"
        
        echo "test_release_url=$TEST_RELEASE_URL" >> $GITHUB_OUTPUT
        echo "test_staging_url=$TEST_STAGING_URL" >> $GITHUB_OUTPUT
        echo "test_script=$TEST_ENTRY_POINT" >> $GITHUB_OUTPUT
        echo "s3_base_target=$S3_BASE_TARGET" >> $GITHUB_OUTPUT
