name: Master Build 3
run-name: ${{ github.event.workflow_run.display_title }}
on:
  workflow_run:
    workflows: [ "Master Build 2" ]
    types:
      - completed
jobs:
  create_and_save_run_number:
    runs-on: ubuntu-latest
    steps:
      - name: Print Run Number
        run: echo "Build 3 Run_number ${{ github.run_number }}"