name: Master Build 2
on:
  workflow_run:
    workflows: ["Master Build 1"]
    types:
      - completed

# Set a dynamic run name for this workflow.
# It uses the run number from the triggering "Build1" workflow.
run-name: B${{ github.event.workflow_run.run_number}} - Master Build 2

jobs:
  build:
    # The job will run on the latest version of Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Print prev workflow run-name
        run: echo ${{ github.event.workflow_run.run_name }}
      - name: Echo prev workflow_run
        run: echo "prev workflow_run ${{ toJSON(github.event.workflow_run) }}"