name: Master Build 3
on:
  workflow_run:
    workflows: ["Master Build 2"]
    types:
      - completed

# Set a dynamic run name for this workflow.
# It uses the build number that was passed as an input.
run-name: B${{ github.event.workflow_run.run_number}} - Master Build 3

jobs:
  use_build_number:
    runs-on: ubuntu-latest
    steps:
      - name: Echo prev workflow_run
        run: echo "prev workflow_run ${{ toJSON(github.event.workflow_run) }}"