name: Master Build 1
run-name: ${{ inputs.triggering_workflow_run_id != '' && format('`#{1}` MasterBuild 1 - Dev-Build by workflow id `# {0}`', inputs.triggering_workflow_run_id, github.run_number) || github.event_name == 'workflow_dispatch' && format('`#{0}` MasterBuild 1 - Dev-Build', github.run_number) || format('`#{1}` {0}', github.event.head_commit.message, github.run_number)}}

on:
  workflow_dispatch:
    inputs:
      triggering_workflow_run_id:
        required: false
        description: "Workflow run ID of the triggering workflow"
  push:
    branches:
      - "main"

jobs:
  create_and_save_run_number:
    runs-on: ubuntu-latest
    steps:
      - name: Print Run Number
        run: echo "Build 1 Run_number ${{ github.run_number }}"