name: Master Build 1
on:
  workflow_dispatch:

run-name: B${{github.run_number}}-Master Build 1

jobs:
  build:
    # The job will run on the latest version of Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Print run number
        run: echo ${{ github.run_number }}
